// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.sonarqube)
}

sonar {
    properties {
        property("sonar.projectKey", "payabli_sdk-android")
        property("sonar.organization", "payabli")
        property("sonar.host.url", "https://sonarcloud.io")
        property("sonar.sourceEncoding", "UTF-8")
        // Binary resources are not source.
        property(
            "sonar.exclusions",
            listOf(
                "**/build/**",
                "**/*.webp",
                "**/*.png",
                "**/*.jpg",
                "**/*.jpeg",
                "**/*.gif",
                "**/*.ttf",
                "**/*.otf",
            ).joinToString(","),
        )
        // Coverage only, so these files still get issue detection. A `platform` package binds directly to an
        // Android API with no JVM implementation, Keystore and `android.util.*`, so no unit test can reach a
        // line of it and the instrumented tier is what covers it. Kept as a package rule rather than a list
        // of files, so the boundary is something the code states rather than something this file remembers.
        // See CLAUDE.md "Testing" for what belongs there. A `ui` package is the same case for the same
        // reason: a composable needs a composition, and therefore a device. `:payin` puts every composable
        // under `ui` and every testable type outside it, so this stays a package rule too.
        // A third case, and a different one from the two above: these lines are executed, just not by the
        // module that owns them. The fixtures run from every other module's test task, and JaCoCo runs per
        // module and instruments only that module's own classes, so none of that execution is attributable
        // here. They were test sources before they had a module of their own, which counts toward no
        // module's coverage at all; giving them a `main` source set is what makes them look uncovered.
        // Coverage only, so the fixtures are still analysed for issues and duplication like any other code.
        property("sonar.coverage.exclusions", "**/platform/**,**/sdk/payin/ui/**,**/sdk/testutils/**")

        // Every entry below is one rule over one path. `@Suppress("LongParameterList")` was tried first and
        // the analyser does not honour it: the issue was still reported on the commit carrying it, so the
        // annotation is gone rather than left looking like it did something.
        property(
            "sonar.issue.ignore.multicriteria",
            "copyMirrorsItsProperties,formEntryComposable,formContentComposables",
        )

        // A hand-written `copy()` takes one parameter per property, which is what makes it a copy.
        // `PayInFormConfiguration` holds nine, so S107 counts nine and reports them. The same
        // signature generated by a `data class` is not reported, and the class is a plain one only
        // so that its copy reads the defensive copies rather than the caller's own collections.
        property("sonar.issue.ignore.multicriteria.copyMirrorsItsProperties.ruleKey", "kotlin:S107")
        property(
            "sonar.issue.ignore.multicriteria.copyMirrorsItsProperties.resourceKey",
            "**/sdk/payin/form/PayInFormConfiguration.kt",
        )

        // A composable's parameters are how a caller configures it, and a parameter object in their place
        // costs the caller the defaults and the trailing-lambda syntax. Both paths hold composables and
        // nothing else, so a long parameter list outside one is still reported.
        property("sonar.issue.ignore.multicriteria.formEntryComposable.ruleKey", "kotlin:S107")
        property(
            "sonar.issue.ignore.multicriteria.formEntryComposable.resourceKey",
            "**/sdk/payin/PayabliPayInForm.kt",
        )
        property("sonar.issue.ignore.multicriteria.formContentComposables.ruleKey", "kotlin:S107")
        property(
            "sonar.issue.ignore.multicriteria.formContentComposables.resourceKey",
            "**/sdk/payin/ui/**",
        )
    }
}

// The sample app is not the SDK. It has no consumers, it is not published, and a rating that moves
// because a demo screen changed says nothing about the artifact a partner links. Skipping the project
// drops it from `sonar.modules`, so its issues, duplication and uncovered lines are all out of the
// project's numbers, and no path glob has to keep track of where its packages live. CI still builds,
// tests, lints and formats it; the results report nowhere.
project(":example") {
    sonar {
        isSkipProject = true
    }
}

// Where each analyser writes, so Sonar reads the reports the build already produced.
subprojects {
    sonar {
        properties {
            val reports = layout.buildDirectory.dir("reports").get().asFile

            // Enumerated: this property is a comma-separated list, not a glob.
            //
            // The test is for Kotlin under the source set, not for the source set. ktlint reports
            // NO-SOURCE and writes no file for a source set holding no `.kt`, and Sonar then warns
            // that a named report is missing, which is a warning nobody can act on: three fired at
            // once, for the two template-only modules whose `src/main` is still empty and for the
            // sample app's `src/debug`, which holds a manifest and one XML.
            fun hasKotlin(sourceSet: String): Boolean =
                layout.projectDirectory
                    .dir("src/$sourceSet")
                    .asFile
                    .walkTopDown()
                    .any { it.isFile && it.extension == "kt" }

            val ktlintTasks = buildList {
                add("ktlintKotlinScriptCheck")
                if (hasKotlin("main")) add("ktlintMainSourceSetCheck")
                if (hasKotlin("test")) add("ktlintTestSourceSetCheck")
                if (hasKotlin("androidTest")) add("ktlintAndroidTestSourceSetCheck")
                if (hasKotlin("debug")) add("ktlintDebugSourceSetCheck")
            }
            property(
                "sonar.kotlin.ktlint.reportPaths",
                ktlintTasks.joinToString(",") { "$reports/ktlint/$it/$it.xml" },
            )

            // Which variant writes the reports. The sample app is the only module with product flavors, so
            // every report it produces is variant-qualified and nothing it writes is called `debug`. One
            // flavor is the source: the two differ by a dependency and by no code of the app's own, so
            // reporting both would measure the same lines twice. Named here rather than derived, because a
            // path that does not exist is not an error in Sonar. It is a warning, and the module reports as
            // unmeasured.
            val isFlavored = path == ":example"
            val coveragePath = if (isFlavored) "withTelemetry/debug" else "debug"
            val lintVariant = if (isFlavored) "withTelemetryDebug" else "debug"

            // Set only where the producing task exists.
            plugins.withId("com.android.library") {
                property("sonar.androidLint.reportPaths", "$reports/lint-results-$lintVariant.xml")
            }
            plugins.withId("com.android.application") {
                property("sonar.androidLint.reportPaths", "$reports/lint-results-$lintVariant.xml")
            }
            if (layout.projectDirectory.dir("src/test").asFile.isDirectory) {
                property(
                    "sonar.coverage.jacoco.xmlReportPaths",
                    "$reports/coverage/test/$coveragePath/report.xml",
                )
            }
        }
    }
}
