// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.sonarqube)
}

sonar {
    properties {
        property("sonar.projectKey", "payabli_sdk-android")
        property("sonar.organization", "payabli")
        property("sonar.host.url", "https://sonarcloud.io")
        property("sonar.sourceEncoding", "UTF-8")
        // Binary resources are not source.
        property(
            "sonar.exclusions",
            listOf(
                "**/build/**",
                "**/*.webp",
                "**/*.png",
                "**/*.jpg",
                "**/*.jpeg",
                "**/*.gif",
                "**/*.ttf",
                "**/*.otf",
            ).joinToString(","),
        )
        // Coverage only, so these files still get issue detection. A `platform` package binds directly to an
        // Android API with no JVM implementation, Keystore and `android.util.*`, so no unit test can reach a
        // line of it and the instrumented tier is what covers it. Kept as a package rule rather than a list
        // of files, so the boundary is something the code states rather than something this file remembers.
        // See CLAUDE.md "Testing" for what belongs there. A `ui` package under the sample app is the
        // same case for the same reason: a composable needs a composition, and therefore a device.
        // The sample app puts every composable under `ui` and every testable type outside it so this
        // stays a package rule too, and `:payin` follows the same layout for its form component.
        property("sonar.coverage.exclusions", "**/platform/**,**/example/app/demo/ui/**,**/sdk/payin/ui/**")

        // Every entry below is one rule over one path. `@Suppress("LongParameterList")` was tried first and
        // the analyser does not honour it: the issue was still reported on the commit carrying it, so the
        // annotation is gone rather than left looking like it did something.
        property(
            "sonar.issue.ignore.multicriteria",
            "copyMirrorsItsProperties,formEntryComposable,formContentComposables,demoComposables",
        )

        // A hand-written `copy()` takes one parameter per property, which is what makes it a copy.
        // `PayInFormConfiguration` holds nine, so S107 counts nine and reports them. The same
        // signature generated by a `data class` is not reported, and the class is a plain one only
        // so that its copy reads the defensive copies rather than the caller's own collections.
        property("sonar.issue.ignore.multicriteria.copyMirrorsItsProperties.ruleKey", "kotlin:S107")
        property(
            "sonar.issue.ignore.multicriteria.copyMirrorsItsProperties.resourceKey",
            "**/sdk/payin/form/PayInFormConfiguration.kt",
        )

        // A composable's parameters are how a caller configures it, and all but the required few carry
        // defaults: `PayabliPayInForm` takes a flow, an operation and a configuration, then seven optional
        // ones, and Material3's own `TextField` takes over twenty. A parameter object in their place costs a
        // caller the defaults and the trailing-lambda syntax. The three paths hold the composables and
        // nothing else, so a long parameter list outside a composable is still reported.
        property("sonar.issue.ignore.multicriteria.formEntryComposable.ruleKey", "kotlin:S107")
        property(
            "sonar.issue.ignore.multicriteria.formEntryComposable.resourceKey",
            "**/sdk/payin/PayabliPayInForm.kt",
        )
        property("sonar.issue.ignore.multicriteria.formContentComposables.ruleKey", "kotlin:S107")
        property(
            "sonar.issue.ignore.multicriteria.formContentComposables.resourceKey",
            "**/sdk/payin/ui/**",
        )
        property("sonar.issue.ignore.multicriteria.demoComposables.ruleKey", "kotlin:S107")
        property(
            "sonar.issue.ignore.multicriteria.demoComposables.resourceKey",
            "**/example/app/demo/ui/**",
        )
    }
}

// Where each analyser writes, so Sonar reads the reports the build already produced.
subprojects {
    sonar {
        properties {
            val reports = layout.buildDirectory.dir("reports").get().asFile

            // Enumerated: this property is a comma-separated list, not a glob.
            //
            // The test is for Kotlin under the source set, not for the source set. ktlint reports
            // NO-SOURCE and writes no file for a source set holding no `.kt`, and Sonar then warns
            // that a named report is missing, which is a warning nobody can act on: three fired at
            // once, for the two template-only modules whose `src/main` is still empty and for the
            // sample app's `src/debug`, which holds a manifest and one XML.
            fun hasKotlin(sourceSet: String): Boolean =
                layout.projectDirectory
                    .dir("src/$sourceSet")
                    .asFile
                    .walkTopDown()
                    .any { it.isFile && it.extension == "kt" }

            val ktlintTasks = buildList {
                add("ktlintKotlinScriptCheck")
                if (hasKotlin("main")) add("ktlintMainSourceSetCheck")
                if (hasKotlin("test")) add("ktlintTestSourceSetCheck")
                if (hasKotlin("androidTest")) add("ktlintAndroidTestSourceSetCheck")
                if (hasKotlin("debug")) add("ktlintDebugSourceSetCheck")
            }
            property(
                "sonar.kotlin.ktlint.reportPaths",
                ktlintTasks.joinToString(",") { "$reports/ktlint/$it/$it.xml" },
            )

            // Set only where the producing task exists.
            plugins.withId("com.android.library") {
                property("sonar.androidLint.reportPaths", "$reports/lint-results-debug.xml")
            }
            plugins.withId("com.android.application") {
                property("sonar.androidLint.reportPaths", "$reports/lint-results-debug.xml")
            }
            if (layout.projectDirectory.dir("src/test").asFile.isDirectory) {
                property(
                    "sonar.coverage.jacoco.xmlReportPaths",
                    "$reports/coverage/test/debug/report.xml",
                )
            }
        }
    }
}
