// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.sonarqube)
}

sonar {
    properties {
        property("sonar.projectKey", "payabli_sdk-android")
        property("sonar.organization", "payabli")
        property("sonar.host.url", "https://sonarcloud.io")
        property("sonar.sourceEncoding", "UTF-8")
        // Binary resources are not source.
        property(
            "sonar.exclusions",
            listOf(
                "**/build/**",
                "**/*.webp",
                "**/*.png",
                "**/*.jpg",
                "**/*.jpeg",
                "**/*.gif",
                "**/*.ttf",
                "**/*.otf",
            ).joinToString(","),
        )
        // Coverage only, so these files still get issue detection. A `platform` package binds directly to an
        // Android API with no JVM implementation, Keystore and `android.util.*`, so no unit test can reach a
        // line of it. Kept as a package rule rather than a list of files, so the boundary is something the
        // code states rather than something this file remembers. See CLAUDE.md "Testing" for what belongs
        // there.
        //
        // The analysis now reads the instrumented tier too, so "a unit test cannot reach it" stopped being a
        // reason on its own. What keeps `platform` excluded is narrower and specific to it: part of what
        // covers it is hardware the emulator job does not have. Two of :core's platform tests assert the
        // storage and device keys are in secure hardware at the device's best level, which an emulator fails
        // outright with SECURITY_LEVEL_SOFTWARE, so they carry @ManualDeviceTest and no automated run
        // executes them. Measured on a handset with that tier excluded, exactly as the job runs it, the
        // `platform` packages read 72.0% line. Including them would gate new code on a number no automated
        // run can complete. Revisit this against a measurement, not against the shape of the rule.
        //
        // `ui` is not that case and is no longer excluded. A composable needs a composition and therefore a
        // device, and the emulator is a device: nothing in :payin's form needs hardware the job lacks. The
        // rule also never covered what it claimed to, which is how it was found — PayabliPayInForm sits
        // outside `ui`, so 11 of its lines counted against the gate while the exclusion said the UI was
        // handled.
        //
        // A second case, and a different one from the above: these lines are executed, just not by the
        // module that owns them. The fixtures run from every other module's test task, and JaCoCo runs per
        // module and instruments only that module's own classes, so none of that execution is attributable
        // here. They were test sources before they had a module of their own, which counts toward no
        // module's coverage at all; giving them a `main` source set is what makes them look uncovered.
        // Coverage only, so the fixtures are still analysed for issues and duplication like any other code.
        //
        // A third, and the only one that is about what a file is rather than what can reach it: the sample
        // app and its token server are not shipped. Nothing an integrator installs contains a line of them,
        // so a coverage figure over them measures how thoroughly the demonstration is tested and reports it
        // as though it were the product. Every module that IS the product stays measured, composables now
        // included. Coverage only, again, so the sample is still analysed for issues and duplication.
        property(
            "sonar.coverage.exclusions",
            listOf(
                "**/platform/**",
                "**/sdk/testutils/**",
                "**/com/payabli/example/**",
                "example-server/**",
            ).joinToString(","),
        )

        // Every entry below is one rule over one path. `@Suppress("LongParameterList")` was tried first and
        // the analyser does not honour it: the issue was still reported on the commit carrying it, so the
        // annotation is gone rather than left looking like it did something.
        property(
            "sonar.issue.ignore.multicriteria",
            "copyMirrorsItsProperties,formEntryComposable,formContentComposables",
        )

        // A hand-written `copy()` takes one parameter per property, which is what makes it a copy.
        // `PayInFormConfiguration` holds nine, so S107 counts nine and reports them. The same
        // signature generated by a `data class` is not reported, and the class is a plain one only
        // so that its copy reads the defensive copies rather than the caller's own collections.
        property("sonar.issue.ignore.multicriteria.copyMirrorsItsProperties.ruleKey", "kotlin:S107")
        property(
            "sonar.issue.ignore.multicriteria.copyMirrorsItsProperties.resourceKey",
            "**/sdk/payin/form/PayInFormConfiguration.kt",
        )

        // A composable's parameters are how a caller configures it, and a parameter object in their place
        // costs the caller the defaults and the trailing-lambda syntax. Both paths hold composables and
        // nothing else, so a long parameter list outside one is still reported.
        property("sonar.issue.ignore.multicriteria.formEntryComposable.ruleKey", "kotlin:S107")
        property(
            "sonar.issue.ignore.multicriteria.formEntryComposable.resourceKey",
            "**/sdk/payin/PayabliPayInForm.kt",
        )
        property("sonar.issue.ignore.multicriteria.formContentComposables.ruleKey", "kotlin:S107")
        property(
            "sonar.issue.ignore.multicriteria.formContentComposables.resourceKey",
            "**/sdk/payin/ui/**",
        )
    }
}

// The sample app is not the SDK. It has no consumers, it is not published, and a rating that moves
// because a demo screen changed says nothing about the artifact a partner links. Skipping the project
// drops it from `sonar.modules`, so its issues, duplication and uncovered lines are all out of the
// project's numbers, and no path glob has to keep track of where its packages live. CI still builds,
// tests, lints and formats it; the results report nowhere.
project(":example") {
    sonar {
        isSkipProject = true
    }
}

// Where each analyser writes, so Sonar reads the reports the build already produced.
subprojects {
    sonar {
        properties {
            val reports = layout.buildDirectory.dir("reports").get().asFile

            // Enumerated: this property is a comma-separated list, not a glob.
            //
            // The test is for Kotlin under the source set, not for the source set. ktlint reports
            // NO-SOURCE and writes no file for a source set holding no `.kt`, and Sonar then warns
            // that a named report is missing, which is a warning nobody can act on: three fired at
            // once, for the two template-only modules whose `src/main` is still empty and for the
            // sample app's `src/debug`, which holds a manifest and one XML.
            fun hasKotlin(sourceSet: String): Boolean =
                layout.projectDirectory
                    .dir("src/$sourceSet")
                    .asFile
                    .walkTopDown()
                    .any { it.isFile && it.extension == "kt" }

            val ktlintTasks = buildList {
                add("ktlintKotlinScriptCheck")
                if (hasKotlin("main")) add("ktlintMainSourceSetCheck")
                if (hasKotlin("test")) add("ktlintTestSourceSetCheck")
                if (hasKotlin("androidTest")) add("ktlintAndroidTestSourceSetCheck")
                if (hasKotlin("debug")) add("ktlintDebugSourceSetCheck")
            }
            property(
                "sonar.kotlin.ktlint.reportPaths",
                ktlintTasks.joinToString(",") { "$reports/ktlint/$it/$it.xml" },
            )

            // Which variant writes the reports. The sample app is the only module with product flavors, so
            // every report it produces is variant-qualified and nothing it writes is called `debug`. One
            // flavor is the source: the two differ by a dependency and by no code of the app's own, so
            // reporting both would measure the same lines twice. Named here rather than derived, because a
            // path that does not exist is not an error in Sonar. It is a warning, and the module reports as
            // unmeasured.
            val isFlavored = path == ":example"
            val coveragePath = if (isFlavored) "withTelemetry/debug" else "debug"
            val lintVariant = if (isFlavored) "withTelemetryDebug" else "debug"

            // Set only where the producing task exists.
            plugins.withId("com.android.library") {
                property("sonar.androidLint.reportPaths", "$reports/lint-results-$lintVariant.xml")
            }
            plugins.withId("com.android.application") {
                property("sonar.androidLint.reportPaths", "$reports/lint-results-$lintVariant.xml")
            }
            // Both tiers, comma-separated, and Sonar unions them: a line covered on the device counts
            // whether or not a unit test also reaches it. Without the second path an instrumented test
            // contributes nothing to coverage on new code however much it exercises, which measured SDK
            // code that only a device can reach as untested and failed the gate on it.
            //
            // Listed per source set that exists rather than unconditionally, for the reason the comment
            // above `coveragePath` gives: a path that is not there is a warning and an unmeasured module,
            // not an error. That is also why the instrumented job's own artifact step fails on an empty
            // upload, and why the sonar job checks these two files before analysing. Locally, a module
            // whose instrumented tier has not been run reports the same warning, which is correct.
            val coverageReports =
                buildList {
                    if (layout.projectDirectory.dir("src/test").asFile.isDirectory) {
                        add("$reports/coverage/test/$coveragePath/report.xml")
                    }
                    if (layout.projectDirectory.dir("src/androidTest").asFile.isDirectory) {
                        // `connected` is a real directory AGP writes, not a typo for the unit path above:
                        // the device the report came from is part of where it lands. Confirmed by running
                        // the task rather than read off the task name.
                        add("$reports/coverage/androidTest/$coveragePath/connected/report.xml")
                    }
                }
            if (coverageReports.isNotEmpty()) {
                property("sonar.coverage.jacoco.xmlReportPaths", coverageReports.joinToString(","))
            }
        }
    }
}
